# Generated by Django 4.1.6 on 2023-02-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('fechanacimiento', models.TimeField()),
                ('contrasenia', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
