TYPE_CHOICES = [('ADM','ADMINISTRADOR'), ('MOD', 'MODERADOR'), ('CRE', 'CREADOR'), ('BAN', 'BANEADO')]
PRIVACY_CHOICES = [('1', 'PUBLICO'), ('0', 'PRIVADO')]
MODERATOR_CHOICES = [('AUT', 'AUTORIZADO'), ('NAUT', 'NO AUTORIZADO'), ('PRO', 'EN PROCESO')]