# Generated by Django 4.1.6 on 2023-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_documento_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='documents/category_type'),
        ),
    ]
