# Generated by Django 4.1.6 on 2023-02-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_alter_documento_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtributo',
            fields=[
                ('idtipoatributo', models.BigAutoField(primary_key=True, serialize=False)),
                ('atributo', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'tipoatributo',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='basedocumento',
            name='tipodato',
        ),
        migrations.RemoveField(
            model_name='detalledocumento',
            name='tipodato',
        ),
        migrations.AddField(
            model_name='basedocumento',
            name='idtipoatributo',
            field=models.ForeignKey(blank=True, db_column='idtipoatributo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Documents.tipoatributo'),
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='idtipoatributo',
            field=models.ForeignKey(blank=True, db_column='idtipoatributo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Documents.tipoatributo'),
        ),
    ]
