# Generated by Django 4.1.6 on 2023-02-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_tipoatributo_remove_basedocumento_tipodato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedocumento',
            name='idtipoatributo',
        ),
        migrations.RemoveField(
            model_name='detalledocumento',
            name='idtipoatributo',
        ),
        migrations.AddField(
            model_name='basedocumento',
            name='tipodato',
            field=models.CharField(blank=True, choices=[('text', 'texto'), ('number', 'numerico'), ('date', 'fecha')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalledocumento',
            name='tipodato',
            field=models.CharField(blank=True, choices=[('text', 'texto'), ('number', 'numerico'), ('date', 'fecha')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='atributo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=[('text', 'texto'), ('number', 'numerico'), ('date', 'fecha')]),
        ),
    ]
