# Generated by Django 4.1.6 on 2023-02-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0010_delete_tipoatributo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='resumen',
        ),
    ]
