# Generated by Django 4.1.6 on 2023-02-27 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documents', '0011_remove_documento_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='idtipodocumento',
            field=models.ForeignKey(blank=True, db_column='idtipodocumento', null=True, on_delete=django.db.models.deletion.CASCADE, to='Documents.tipodocumento'),
        ),
    ]
