# Generated by Django 4.1.6 on 2023-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0012_documento_usuario_alter_documento_idtipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
