# Generated by Django 4.1.6 on 2023-02-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0013_documento_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='estado',
        ),
    ]
