# Generated by Django 4.1.6 on 2023-02-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0014_remove_documento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='publico',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='idtipodocumento',
            field=models.ForeignKey(blank=True, db_column='idtipodocumento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Documents.tipodocumento'),
        ),
    ]
