# Generated by Django 4.1.6 on 2023-02-28 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documents', '0015_remove_documento_publico_remove_documento_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
