# Generated by Django 4.1.6 on 2023-03-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0017_documento_usuarioanalista_alter_documento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='valor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
