# Generated by Django 4.1.6 on 2023-03-03 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documents', '0018_alter_detalledocumento_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='usuarioanalista',
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
